
spring:
  datasource:     #数据源配置
    type: com.alibaba.druid.pool.DruidDataSource  #连接池的类型
    password: 123456   #数据库的密码
    username: root     #数据库的账户
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库的驱动程序类
    url: jdbc:mysql://localhost:3306/goods_market_db?serverTimezone=GMT

#mybatis的配置如下
mybatis:
  configuration:
    map-underscore-to-camel-case: true   #数据库表中的下划线自动转换成驼峰
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #mapper文件的路径，这个路径下面的mapper.xml会被自动加载成mybatis映射文件
